
        version: '3.8'
        services:
          db:
            image: mysql:latest
            restart: always
            environment:
              # Password for root access
              MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
            ports:
              # <Port exposed> : < MySQL Port running inside container>
              - '3306:3306'

            volumes:
              - db_data:/var/lib/mysql
        volumes:
          db_data:
            driver: local